### ISSUE TITLE
ajustes-vrt max

### ISSUE THREAD

**Issue by matias4u** [add-ons/plugin.video.vrt.nu#1105]
### To Reproduce ###
1. Go to ...
2. Click on ....
3. Scroll down to ....

### Additional context ###

- Operating system:
- Kodi version:
- Addon version:
- Using a VPN: yes/no
- Country you are using the addon from: ...

### Log (if available) ###
```paste below


```

**Comment by matias4u** [comment]
ajustes-vrt max

**Comment by matias4u** [comment]
kodi appears  on the tela ajustes vrt max

**Comment by matias4u** [comment]
wat i need to know for fix them

**Comment by lebeno** [comment]
@matias4u it is not very clear what you mean. What are you trying to do? What is the expected behavior? What is going wrong or what error do you get?

If it is not easy for you to explain this in English:
je mag hier ook problemen melden in het Nederlands. 
Tu peux également signaler des problèmes ici en français.

**Comment by mediaminister** [comment]
Please reopen this issue if you still need help with the VRT MAX add-on.
