### ISSUE TITLE
VRT Geoblock error despite roaming

### ISSUE THREAD

**Issue by geert-hendrickx-be** [add-ons/plugin.video.vrt.nu#721]
This is a followup on https://github.com/add-ons/plugin.video.vrt.nu/issues/49.

Roaming in EU returns the following error with plugin version 2.3.2

`VRT Geoblock: Roaming settings are incomplete, to enable watching geo-blocked content while roaming please add additional information to the user profile.`

Despite vrtnu login with verified Belgian phone number (roaming works in browser).

Debug log with stack trace: [kodi.log](https://github.com/add-ons/plugin.video.vrt.nu/files/4432154/kodi.log)

**Comment by mediaminister** [comment]
I found the bug, VRT NU has changed something, now a `user_XVRTToken` is needed instead of an ordinary `XVRTToken`. 
Please try this zip package: 
[plugin.video.vrt.nu-2.3.2-fixroaming-e6bd062.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/4432620/plugin.video.vrt.nu-2.3.2-fixroaming-e6bd062.zip)

**Comment by geert-hendrickx-be** [comment]
Unfortunately, now I cannot start any vrt.nu stream anymore, geo-blocked or not: [kodi.log](https://github.com/add-ons/plugin.video.vrt.nu/files/4436457/kodi.log)

**Comment by geert-hendrickx-be** [comment]
Sorry, it works after restarting Kodi, including roaming.  Thanks a lot!
