### ISSUE TITLE
Playback issues on live streams (during or after broadcast ended)

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vrt.nu#812]
### Describe the bug ###

When watching live VRTNU channels the stream is choppy and constantly caching. This is only during LIVE and not when viewing OnDemand content.

### To Reproduce ###
1. Watch Live VRTNU channels, één, canvas,...

### Expected behavior ###

Streams should go smooth, it is only 720p, VTMGO streams at 1080p here are no caching issues.
Tested with Inputstream on and off, same for Widevine...

### Additional context ###

- Operating system: Libreelec 9.2.4
- Kodi version: 18.8
- Addon version: 2.4.0
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below
2020-09-26 12:44:38.493 T:2979001200 WARNING: ActiveAE - large audio sync error: -5908.818155
2020-09-26 12:44:38.493 T:2979001200 WARNING: ActiveAE - large audio sync error: -5908.817044
2020-09-26 12:44:38.494 T:2979001200 WARNING: ActiveAE - large audio sync error: -5907.817174
2020-09-26 12:44:38.494 T:2979001200 WARNING: ActiveAE - large audio sync error: -5907.818433
2020-09-26 12:44:38.572 T:2979001200 WARNING: ActiveAE - large audio sync error: -5958.833747
2020-09-26 12:44:38.622 T:2979001200 WARNING: ActiveAE - large audio sync error: -5958.788489
```

**Comment by dagwieers** [comment]
VRT NU live tv typically is 720p (3Mbps) and VOD is 540p (2Mbps). So I wonder if something in your setup is not able to handle 720p, but can handle 540p. This could be because you are using wifi, or there are other network-related issues at your end or at VRT NU's end, or for whatever reason your box is maxing out at 3Mbps?

If you could restrict the bandwidth usage to 2048kbps in the add-on, does the caching still happen?
See: https://github.com/add-ons/plugin.video.vrt.nu/wiki/Bandbreedte

You can also test using the speedtest add-on to see what your device is capable of doing.

I can attest this is not happening to me on a RPi3B.

**Comment by vermope** [comment]
@dagwieers Wow very fast response, thank you! Also a big thanks for making Belgium television available for Kodi users.

Did all the things you've suggested without luck. Then reinstalled "Retrospect" to see if the issue is also there, In Retrospect the live stream for "één" runs smooth, no caching issues whatsoever..

Reinstalled VRTNU addon, the issue still persists, however I can narrow it down to only the "één" stream,  "Canvas, Ketnet,..." are running fine.

In the logs I see there are alot of large audio sync errors during an "één" livestream..
https://pastebin.com/xA8h9c14 
(some parts are cut because of sizelimit, all the same errors..)


For the record I'm not on Wifi, Hardware is definitely capable for 1080p (x86/x64 Asrock Intel), all other streams work fine, VTMGO / Netflix / VierVijfZes / ....

**Comment by vermope** [comment]
Ik weet niet hoe of wat... maar na het af en aan zetten van de optie "Use Local HTTP Caching" , en mijn credentials een keer te vernieuwen is het probleem opgelost. Ook de errors in de log zijn verdewenen.

**Comment by dagwieers** [comment]
@vermope De local HTTP caching en credentials zouden geen invloed mogen hebben op het afspelen van streams. Maar de audio sync issues lijken mij meer te wijzen op problemen bij VRT NU zelf. Moest het zich opnieuw voordoen zou het interessant zijn moest de VRT NU add-on debug logging hebben aanstaan, dan kunnen we een verband leggen met de manifest.

**Comment by vermope** [comment]
@dagwieers Wanneer het probleem zich opnieuw voordoet stel ik de debug logging in. Wat wel vreemd is dat het het in de Retrospect addon wel vlot liep en die van VRT NU niet... (beide getest in eenzelfde tijdframe) ik vermoed dat beide addons de zelfde streams aanroepen?

**Comment by vermope** [comment]
@dagwieers Unfortunately it appeared that I had cheered too early. The caching issue is still here, as I said before it only happens in the "VRT NU" addon and only when watching "live".

https://pastebin.com/yh90Ad2C

**Comment by dagwieers** [comment]
@vermope I do not see any VRT NU debug output in your log.

**Comment by vermope** [comment]
@dagwieers ->new log:
https://paste.ubuntu.com/p/Fbzk7hWQ3v/

**Comment by ythefoe** [comment]
I recently also have issues when using this add-on.
The stream 'stops' playing for a couple of seconds (usually around 10 seconds) and then catches up by playing the video very fast.
Audio stops also, but doesn't need to catch up. This seems to be inline with the logs of vermope (audio sync error). 

I just watched 'big little lies' on demand, and I got the stream freezing up a couple of times.
I did need to stop the stream and restart the continue.

This issue seems to be started a couple of weeks ago, and I wouldn't be surprissed if the root cause is on the VRT side. 
I'm using an RPi3 connected to the LAN

**Comment by everte** [comment]
Similar here, since a few days (week?) there is a lot of caching/choppiness happening. The previous months I've never had to wait during a stream for buffering and now it happens multiple times for nearly every program.

Watching them through vrtnu website goes smooth. I'm not sure what changed.

**Comment by dagwieers** [comment]
Watching through VRT NU website means your player can drop the resolution when your bandwidth can not keep up with the stream (this is called adaptive bitrate streaming). Unfortunately Kodi does not do this yet (despite the library being named **inputstream.adaptive** it is not adaptive yet), it picks the highest resolution possible (according to your settings) and plays it. If it is not sufficient, you get the behaviour you see.

So I would not rule out that your bandwidth or network behaviour has changed. Try to reset your Wifi AP, cable modem or check with your provider. My parents had bandwidth issues and after reporting it to their provider they did something to reinstate the bandwidth they should have had. I have heard of similar practices elsewhere.

Try fast.com to test if you get the desired bandwidth. There is also a speedtest add-on in Kodi you can use.

If all else fails, it might also be related to VRT NU infrastructure being oversubscribed (e.g. more and more students nowadays stream online). I have not seen any problems myself, but I usually watch very late at night.

**Comment by dagwieers** [comment]
@vermope Also, can you try to turn of DRM / Widevine and see if this helps. I can see audio sync issues in the log and this could also potentially be related to hardware. It is possible that DRM is disabled in Retrospect, which would explain why it behaves differently in your case. Can you also tell me what hardware you are using to run Kodi?

**Comment by dagwieers** [comment]
Also I noticed some tweaks in the advancedsettings.xml of both the system as well as your profile.

I would get rid of both and test with the defaults. I do not think you should be modifying buffer, caching and memory settings. Even if it was to test if it would improve, do not leave that lingering.

**Comment by dagwieers** [comment]
I was playing the 720p live stream today in the background and I see the exact same thing happening here, right now.
Let me check a few things and come back t you ;-)

**Comment by vermope** [comment]
@dagwieers Yes, your analysis is correct, it seems that the laggy behavior got worse by the day. I'm even encountering choppy playback during some on demand videos eg. "Dwars door België", "Journaal"..

**Comment by dagwieers** [comment]
I have now been experiencing the same thing with the VTM GO add-on (which is 1080p). Might be unrelated, but maybe it is related to a change in Kodi v18.8 player?

**Comment by vermope** [comment]
@dagwieers Yesterday I've watched "Snackmasters" live with no issues whatsoever.

**Comment by wimpunk** [comment]
As reported on facebook, I have a pretty similar problem.  How can I easily reset the advanced settings back to basics?  I know I've done some tuning a while ago, so as suggested by @dagwieers resetting could be a good solution.

**Comment by dagwieers** [comment]
@wimpunk The advanced settings are not managed by Kodi, so the only thing you can do is remove everything (that is not essential) from the advancedsettings.xml.

In Kodi itself, you can only reset settings per settings page. → *Reset above settings to default*

LibreELEC has in its settings an options to reset Kodi and LibreELEC to defaults.

- **Kodi Settings » LibreELEC » System » Reset to Defaults » Reset System Settings to default**
- **Kodi Settings » LibreELEC » System » Reset to Defaults » Reset LibreELEC to defaults**

**Comment by vermope** [comment]
FIY: I've played live VRT for the last 3 hours in the background without any hiccups or caching annoyances. Neither are there any log entries that indicate any streaming (audio) issue.

**Comment by mediaminister** [comment]
Which ISP do you have?
At what time do the problems arise?

I suspect this might be a bandwidth issue during peak hours.

**Comment by vermope** [comment]
ISP is Telenet... Bandwidth, hmm, you think on the VRT NU side? Or ISP side? Because streaming other things, on higher quality, thus higher bandwidth doesn't give any problems. Things like Netflix, VTM Go or "other" streams go very fluently, even on peak hours.

**Comment by mediaminister** [comment]
I don't know, I might be wrong. I ask this to be able to rule out certain causes.
If you never experienced this during peak hours with a VTM GO livestream, than it might be related to VRT NU back-end or to this add-on.

**Comment by dagwieers** [comment]
Vanavond heb ik een heel ander soort gedrag opgemerkt, voor het eerst.
```log
2020-10-05 23:44:43.760 T:732951424   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2020-10-05 23:44:43.770 T:732951424   ERROR: CCurlFile::Open failed with code 0 for https://remix-cf.lwc.vrtcdn.be/remix/a6c844df-9913-4725-b286-42c57a7709c6/remix.ism/dash/remix-video=1998764-401430.dash:
2020-10-05 23:45:03.797 T:808444800   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2020-10-05 23:45:03.797 T:808444800   ERROR: CCurlFile::Open failed with code 0 for https://remix-cf.lwc.vrtcdn.be/remix/a6c844df-9913-4725-b286-42c57a7709c6/remix.ism/dash/remix-audio=96000-32160768.dash:
2020-10-05 23:45:23.829 T:874505088   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2020-10-05 23:45:23.829 T:874505088   ERROR: CCurlFile::Open failed with code 0 for https://remix-cf.lwc.vrtcdn.be/remix/a6c844df-9913-4725-b286-42c57a7709c6/remix.ism/dash/remix-textstream_dut=1000-723050.dash:
2020-10-05 23:45:23.972 T:963629952  NOTICE: CVideoPlayer::OnExit()
2020-10-05 23:45:23.972 T:963629952  NOTICE: VideoPlayer: eof, waiting for queues to empty
2020-10-05 23:45:23.973 T:963629952  NOTICE: Closing stream player 1
```

Ook hier krijg je geen buffering te zien op het scherm, playback hangt en na en 20tal seconden ga je terug naar het menu en krijg je een VRT NU pop-up dat er een probleem was.

**Comment by geert-hendrickx-be** [comment]
Ook hier de laatste tijd regelmatig last van "stream stalled" en "large audio sync error", vooral 's avonds.  Ik denk wel dat dit fenomeen recenter is dan de Kodi 18.8 release.  Platform: Arch Linux op Intel NUC, bedrade connectie, zeker geen netwerk issue.  
Mijn advancedsettings.xml reeds backed out, geen verschil.

**Comment by Dre62** [comment]
Here the same problem as ythefoe  describes since about weeks. Yesterday tried website + Build-in chromecast on our Sony TV, and also buffering problems. Watching online didn't give any problem. I'm convinced yhis is a problem with their server or bandwith at peak moments. I contacted VRT and they finally answered me they are investigating it.

**Comment by dagwieers** [comment]
@Dre62 Did you mention this URL to them? In prior communication we included a link to the ticket so they have the full details of all reported issues and can track new reports.

**Comment by Dre62** [comment]
I didn't mention this URL to them, since I only afterwards checked this forum. The comments I read here are different cases or problems to me. A few days ago I had no problem at all when watching one episode od Babylon Berlin (45') around 8 to 9 PM. When starting a second episode after a few minute we had buffering issues. We stopped it and started watching live without any problem. That's what is convincing to me that de VOD demands don't work well anymore o peak moments. As far as I know, live IP TV is a multicast stream and thus the same load for the server Independent from the number of watchers. Another evening, when the problem started I switched over to the vrtnu website on my pc and casted the video to my tv. The buffering problem was still there, but I didn't have the problem that after filling the buffer Kodi seems to catch up the time by playing the missed part at high speed. Sometimes with Kodi the sound is lost, too, and I have to stop and restart the video to make it work again. That kind of problems I didn't have via casting, but the source of the buffering problem is probably the same.
I'll send the URL as a reply on their mail, but Kodi is not supported by VRT so I don't know if they care about it. What I did is send them a Wireshark trace taken from my pc while casting, but it would be better to make one while watching on the pc itself. I suppose the videostream goes directly to the tv when casting, and is not forked through the pc. I don't know much about it but for me it would be logical to use direct media routing. I have knowledge about IP telephony, which is in fact the same technology.

**Comment by dagwieers** [comment]
We experienced again issues when playing Undercover last night between 21h and 22h. The non-debug logs did not contain any unusual errors, but playback stalled a few times. One time Kodi restarted, but the crashlog doesn't help pinpoint the issue.

**Comment by peno64** [comment]
Note that the title and message says that this happens only when live content is streamed. This is not true. This also happens with for example het journaal 1 hour after it was live. I have seen it several times as such and someone on kodi vlaanderen also says that it happens when reviewing the news.

**Comment by mediaminister** [comment]
FYI, a livestream cache is used to offer current affair programs "on demand" right after the live broadcast. The same livestream is used with a couple of timestamp parameters added to the url.

**Comment by peno64** [comment]
@tatankat 
Interesting observation at the end: We continued to watch using the web viewer which clearly adapted the resolution every time it was not able to follow
So actually you are giving here a temporary work-around.

How is it clear to you that the web viewer switches resolution?

**Comment by dagwieers** [comment]
So the big missing part in **inpustream.adaptive** is the ability to be *adaptive*, but change may be coming sooner than expected?
https://github.com/peak3d/inputstream.adaptive/pull/506

**Comment by tatankat** [comment]
I would not be too enthusiast about this as I only saw this during connection issues (ping packet losses) to vrt nu (which did only happen once). It was clear resolution was changing as we saw the image quality change several times.
Also, when I see the buffering issues, the stream simply stalls completely, not just going slower. I fear this will also be the case when using lower quality video.
If I compile inputstream.adaptive with that pull request, I assume it will not switch resolutions out of the box?

**Comment by geert-hendrickx-be** [comment]
I tried a few client-side workarounds, like [increasing kodi cache](https://kodi.wiki/view/HOW-TO:Modify_the_video_cache) (so the larger buffer could overcome interruptions) or [reducing the bandwidth/quality](https://github.com/add-ons/plugin.video.vrt.nu/wiki/Bandbreedte).  This made the symptoms vary a bit (frozen image followed by "fast forward", no audio, spinner, ...), but the underlying issue remains.  This is annoying because at times VRTnu is hardly usable anymore. :-(

**Comment by mediaminister** [comment]
Does anyone have buffering problems using a FTTH or DSL service provider (Proximus, Scarlet, ..)? Anyone with buffering problems seems to have Telenet? Maybe related to some overloaded proxy between VRT en Telenet? You can try with a VPN service to rule this out.

**Comment by Dorme** [comment]
Indeed, I also have Telenet. I'll try with a vpn when the buffering issue occurs again.

**Comment by geert-hendrickx-be** [comment]
Telenet as well here.

**Comment by dagwieers** [comment]
If you have issues and have Telenet, add a :+1: to this comment.
If you have issues and do not have Telenet (e.g. Proximus, Scarlet, etc.), add a :-1: to this comment.

**Comment by peno64** [comment]
I have telenet, but I also use a vpn which is always on (NordVPN) and I had buffering issues watching "het journaal" the last week or two. Yesterday however I had no problem at at (around 20h30 - 21h15).

**Comment by peno64** [comment]
I am thinking now that it could be I was working with kodi 19 without vpn at the moment I had the buffering... I used it several times last weeks to watch Disney+ because it works better on kodi 19 than 18 and it does not allow a vpn...
Yesterday evening I was for sure working on kodi 18 with vpn and thus no buffering.

**Comment by tatankat** [comment]
Right now, at least since 21h50, it is really bad (loading every few minutes) on our Pi running Kodi. Using the web viewer, the same video (but further in the stream to rule out some caching) is running fine. (trying to watch "Croatia's Wetlands of the Sava") No lost packets detected.

**Comment by dagwieers** [comment]
We have been experiencing issues as well around that time, although restarting the stream worked every time to continue watching.

**Comment by geert-hendrickx-be** [comment]
Yesterday evening it was almost impossible to watch "het journaal" (not live).  Had to restart the stream almost every minute...

**Comment by mediaminister** [comment]
I did some more testing and I found out this problem is caused by a very slowly responding VRT NU streaming CDN.

The MPEG-DASH streams which are handled by the InputStream Adaptive plugin are heavily impacted because adaptive bitrate switching isn't implemented in the plugin. But it seems the HLS-streams which are played directly in Kodi Player suffer less from this problem.

Disabling InputStream Adaptive in the VRT NU add-on "Expert" settings makes sure HLS-streams are always selected and this may reduce these playback issues:
![kodi](https://user-images.githubusercontent.com/45148099/96442260-1fa85d80-120b-11eb-9bce-ad24fc937d70.png)

**Comment by mram65** [comment]
Since mid September, I also have the problem as described in this issue (on Raspberry PI 3B+).

Note that I never watch livestreams (so only VOD-streams).
Since one week now, I deactivated Widevine DRM, and the problem looks solved.
Apparently, Widevine DRM is (temporary) not needed for livestreams in 720p)

**Comment by ghen2** [comment]
> Disabling InputStream Adaptive in the VRT NU add-on "Expert" settings makes sure HLS-streams are always selected and this may reduce these playback issues.

FWIW, I haven't experienced a single streaming issue anymore since making this change.

**Comment by vermope** [comment]
@ghen2 I can confirm, last days everything ran smooth, live TV and VOD.

**Comment by Roel** [comment]
FYI, I didn't change the InputStream settings (i.e. it is still on), and I haven't noticed any hiccups either the last week or two.

**Comment by tatankat** [comment]
Everything runs fine now, I guess VRT fixed it and upgraded some equipment. Thanks VRT & addon devs for your work!

**Comment by mediaminister** [comment]
Please reopen this issue if anyone is experiencing this problem again.

**Comment by yorickps** [comment]
Same issue appeared again during / on New Year's eve, I guess the CDN can not handle too many viewers...

```bash
022-01-01 00:27:50.866 T:27069    INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-01 00:27:51.404 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12935.513916
2022-01-01 00:27:51.404 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12985.725342
2022-01-01 00:27:51.405 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12986.010742
2022-01-01 00:27:51.405 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12936.129150
2022-01-01 00:27:51.405 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12936.268311
2022-01-01 00:27:51.405 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12935.404297
2022-01-01 00:27:51.499 T:2381  WARNING <general>: ActiveAE - large audio sync error: -13168.078613
2022-01-01 00:27:51.562 T:2381  WARNING <general>: ActiveAE - large audio sync error: -13168.083740
2022-01-01 00:27:51.563 T:2381  WARNING <general>: ActiveAE - large audio sync error: -13118.080566
2022-01-01 00:27:51.563 T:2381  WARNING <general>: ActiveAE - large audio sync error: -13067.080322
2022-01-01 00:27:51.563 T:2381  WARNING <general>: ActiveAE - large audio sync error: -13017.080078
2022-01-01 00:27:51.563 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12968.080322
2022-01-01 00:27:51.594 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12918.081055
2022-01-01 00:27:51.657 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12868.083740
2022-01-01 00:27:51.689 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12817.095947
2022-01-01 00:27:51.689 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12768.095215
2022-01-01 00:27:51.690 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12718.095459
2022-01-01 00:27:51.691 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12668.095215
2022-01-01 00:27:51.691 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12617.095459
2022-01-01 00:27:51.691 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12567.094971
2022-01-01 00:27:51.691 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12518.095459
2022-01-01 00:27:51.691 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12468.095215
2022-01-01 00:27:51.691 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12418.095459
2022-01-01 00:27:51.752 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12417.097900
2022-01-01 00:27:51.752 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12368.096924
2022-01-01 00:27:51.752 T:2381  WARNING <general>: ActiveAE - large audio sync error: -12318.097168
```

**Comment by fretb** [comment]
I recently started having the same issues too:

2022-01-26 06:57:51.464 T:5754  WARNING <general>: OutputPicture - timeout waiting for buffer
2022-01-26 06:57:53.514 T:788   WARNING <general>: ActiveAE - large audio sync error: -1137.597900
2022-01-26 06:57:53.652 T:788   WARNING <general>: ActiveAE - large audio sync error: -1183.705566
2022-01-26 06:57:53.653 T:788   WARNING <general>: ActiveAE - large audio sync error: -1177.705322
2022-01-26 06:57:53.654 T:788   WARNING <general>: ActiveAE - large audio sync error: -1177.668213
2022-01-26 06:57:53.748 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-26 06:58:03.954 T:5756     INFO <general>: Skipped 2 duplicate messages..
2022-01-26 06:58:03.954 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-26 06:58:13.225 T:1340     INFO <general>: Skipped 2 duplicate messages..
2022-01-26 06:58:13.225 T:1340     INFO <general>: JSONRPC Server: Disconnection detected
2022-01-26 06:58:16.171 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-26 06:58:28.344 T:5756     INFO <general>: Skipped 2 duplicate messages..
2022-01-26 06:58:28.344 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-26 06:58:40.725 T:5756     INFO <general>: Skipped 2 duplicate messages..
2022-01-26 06:58:40.725 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-26 06:58:52.869 T:5756     INFO <general>: Skipped 2 duplicate messages..
2022-01-26 06:58:52.869 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-26 06:59:05.636 T:5756     INFO <general>: Skipped 2 duplicate messages..
2022-01-26 06:59:05.636 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2022-01-26 06:59:17.769 T:5756     INFO <general>: Skipped 2 duplicate messages..
2022-01-26 06:59:17.769 T:5756     INFO <general>: CVideoPlayerAudio::Process - stream stalled

**Comment by eboelens** [comment]
same problem here

**Comment by eboelens** [comment]
https://paste.osmc.tv/rinodateri

lot of buffering…

especially in films, series and documentaries in the vrt.nu add-on
netflix for example is no problem

reproduce:
add-on: plugin.video.vrt.nu
select a movie
and BAM buffering instant or after some seconds…

Raspberry Pi 4 Model B 8Gb + HIFIBERRY DIGI+ STANDARD

i’m not sure but the problems started with the last upgrade of Osmc I think

I hope you can check the log
Thanks in advance
erik
