### ISSUE TITLE
Add Landscape Integrated View

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vrt.nu#822]
I don't know whether this is the right place to ask but I think this is an addon specific setting. Is it possible to add the "Landscape Integrated View"? 
I use it for all my "Arctic Horizon" views... I believe it used to be integrated as well... VRT NU is the only addon where I can't choose this view.

**Comment by mediaminister** [comment]
Can you add some screenshots? I don't know what "Landscape Integrated View" should look like and what is wrong with the current views.

**Comment by vermope** [comment]
Of course there's nothing wrong with current views, my OCD just likes things neat and tidy :). 
This is what I mean: https://imgur.com/a/nH7HYYt

**Comment by michaelarnauts** [comment]
I think this is related to the type we pass in setContent.

**Comment by mediaminister** [comment]
Thanks for the screenshots. I guess I need to add the right variables to `setInfo`, `setArt` and `setContent`.
I can't get it working for now, but I'll investigate how to enable the "Landscape Integrated" view

**Comment by dagwieers** [comment]
I have a feeling we have to drop the folders-view then. And both videos, seasons and series all will show the same.

Unless we fix this in Kodi. We probably should.

**Comment by vermope** [comment]
Thanks guys for looking into this! Much appreciated.

**Comment by mediaminister** [comment]
> I have a feeling we have to drop the folders-view then. 
Yes, I changed the `file` listings to `tvshow` listings  and added the `season` listing which enables the integrated landscape view.

**Comment by mediaminister** [comment]
@vermope I fixed your issue in https://github.com/add-ons/plugin.video.vrt.nu/pull/823 but this reintroduces another issue https://github.com/add-ons/plugin.video.vrt.nu/issues/783

So, I guess there is a bug in the Arctic Horizon skin and finding and fixing this bug will take more time.
I found out skin.video.siren is setting metadata in the play function to workaround this bug.  This kind of workaround is not desirable in the VRT NU add-on because we need an extra API request for that and this will slow down player start.

**Comment by vermope** [comment]
@mediaminister Ok, no problem. This is certainly nothing urgent.

**Comment by vermope** [comment]
As far as I'm concerned, this may be closed. I have switched to Arctic Horizon 2. AH2 provides better integration of views, also for the VRT MAX addon.

**Comment by mediaminister** [comment]
Thanks for letting me know. I'll close this.
