### ISSUE TITLE
No more favorites

### ISSUE THREAD

**Issue by david63236** [add-ons/plugin.video.vrt.nu#979]
After the last update (version 2.5.10), the addon has no more favorites (empty favorites list),
but if you enter "addon setup / interface / Beheer mijn favorieten" then all the favorites are visible.
(( tested on Android TV and Windows ))

**Comment by mediaminister** [comment]
This problem is not related to the last update.

To show favorite programs and episodes in a Kodi menu, the add-on needs to collect metadata from a VRT API.
And a couple of days ago, this VRT API returns empty data. So, some menus are broken now.

See https://github.com/add-ons/plugin.video.vrt.nu/issues/975#issuecomment-1122310913

**Comment by david63236** [comment]
It seems solved by the 15dfd07, the favorites appears again and the streams open+play.
== tested on : Matrix on Win, Leia on Win, Leia on Android TV
